apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: py-app-ns
data:
  APP_ENV: "production"
  DB_HOST: "postgres-service"
  DB_NAME: "appdb"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: py-app-ns
type: Opaque
stringData:
  DB_USER: "app_user"
  DB_PASSWORD: "SuperSecretPassword123!"
  FLASK_SECRET_KEY: "my-flask-secret-key"
