apiVersion: v1
kind: ServiceAccount
metadata:
  name: py-app-sa
  namespace: py-app-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: py-app-role
  namespace: py-app-ns
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: py-app-rolebinding
  namespace: py-app-ns
subjects:
  - kind: ServiceAccount
    name: py-app-sa
    namespace: py-app-ns
roleRef:
  kind: Role
  name: py-app-role
  apiGroup: rbac.authorization.k8s.io
